sonar.projectKey=intaqalab-local
sonar.sources=apps,libs
sonar.host.url=http://localhost:9000
sonar.login=sqp_a414e75cc91fc35c9f6ec125e74725472f8d5699

sonar.exclusions=**/node_modules/**, **/dist/**,libs/demos/**

sonar.tests=apps,libs
sonar.test.inclusions=**/*.spec.ts
# Reporte de cobertura combinado
sonar.javascript.lcov.reportPaths=coverage/merged/lcov.info