export enum Role {
  /**
   * INTAQALAB_ADMIN - Administrador sistema
   */
  INTAQALAB_ADMIN = 'INTAQALAB_ADMIN',
  /**
   * ADMINISTRATIVE - Administrativo
   */
  ADMINISTRATIVE =  'ADMINISTRATIVE',
  /**
   * PLANNING_TECHNICIAN - Técnico planificación
   */
  PLANNING_TECHNICIAN = 'PLANNING_TECHNICIAN',
  /**
   * UNIT_TECHNICIAN - Técnico. Unidad
   */
  UNIT_TECHNICIAN =  'UNIT_TECHNICIAN',
  /**
   *  INTAQALAB_VIEWER - Solo Lectura
   */
  INTAQALAB_VIEWER =  'INTAQALAB_VIEWER',
  /**
   * HEAD_ARMAMENT_TRIALS -  Jefatura Área de ensayos de armamento
   */ 
  HEAD_ARMAMENT_TRIALS = 'HEAD_ARMAMENT_TRIALS',
  /**
   * INTAQALAB_TRIAL_ENGINEER - Ingeniero ensayos
   */
  INTAQALAB_TRIAL_ENGINEER = 'INTAQALAB_TRIAL_ENGINEER', 
  /**
   * INTAQALAB_TRIAL_ADMINISTRATIVE - Administrativo ensayos
   */
  INTAQALAB_TRIAL_ADMINISTRATIVE = 'INTAQALAB_TRIAL_ADMINISTRATIVE',
  /**
   * INTAQALAB_SHOOTING_LINE_HEAD - Jefe Linea Tiro
   */
  INTAQALAB_SHOOTING_LINE_HEAD = 'INTAQALAB_SHOOTING_LINE_HEAD', 
  /**
   * INTAQALAB_ARMAMENT_UNIT_HEAD - Jefe Unidad Armamento
   */
  INTAQALAB_ARMAMENT_UNIT_HEAD = 'INTAQALAB_ARMAMENT_UNIT_HEAD',
  /**
   * INTAQALAB_ARMAMENT_UNIT_TECHNICIAN - Técnico Unidad Armamento
   */
  INTAQALAB_ARMAMENT_UNIT_TECHNICIAN = 'INTAQALAB_ARMAMENT_UNIT_TECHNICIAN',
  /**
   * INTAQALAB_MUNITIONS_UNIT_HEAD - Jefe Unidad Municiones
   */
  INTAQALAB_MUNITIONS_UNIT_HEAD = 'INTAQALAB_MUNITIONS_UNIT_HEAD',
  /**
   * INTAQALAB_MUNITIONS_UNIT_TECHNICIAN -  Técnico Unidad Municiones
   */
  INTAQALAB_MUNITIONS_UNIT_TECHNICIAN = 'INTAQALAB_MUNITIONS_UNIT_TECHNICIAN',
  /**
   * INTAQALAB_BALLISTICS_UNIT_HEAD -  Jefe Unidad Balística
   */
  INTAQALAB_BALLISTICS_UNIT_HEAD = 'INTAQALAB_BALLISTICS_UNIT_HEAD',
  /**
   * INTAQALAB_BALLISTICS_UNIT_TECHNICIAN - Técnico Unidad Balística
   */
  INTAQALAB_BALLISTICS_UNIT_TECHNICIAN = 'INTAQALAB_BALLISTICS_UNIT_TECHNICIAN',
  /**
   * INTAQALAB_PLANNING_ANALYSIS_HEAD - Jefe Unidad Planificación y Análisis
   */
  INTAQALAB_PLANNING_ANALYSIS_HEAD = 'INTAQALAB_PLANNING_ANALYSIS_HEAD',
  /**
   * INTAQALAB_TRIAL_CONSULTANT - Consultor Ensayos
   */
  INTAQALAB_TRIAL_CONSULTANT = 'INTAQALAB_TRIAL_CONSULTANT',
  /**
   * INTAQALAB_FIRE_TRIALS_UNIT_HEAD -  Jefe Unidad de Ensayos de fuego - Topografía
   */
  INTAQALAB_FIRE_TRIALS_UNIT_HEAD = 'INTAQALAB_FIRE_TRIALS_UNIT_HEAD', 
  /**
   * INTAQALAB_TOPOGRAPHY_UNIT_TECHNICIAN - Técnico Unidad Ensayos de fuego - Topografía
   */
  INTAQALAB_TOPOGRAPHY_UNIT_TECHNICIAN = 'INTAQALAB_TOPOGRAPHY_UNIT_TECHNICIAN',
}
