import { WidgetId } from '../models';
import type { Widget } from '../models/execution-grid.models';

export const injectWidgets = (): Widget[] => [
  {
    id: 'disparo',
    widgetId: WidgetId.SHOT,
    title: 'Disparo',
    description: 'Introducción de datos del disparo seleccionado',
    category: 'Genéricos',
    badge: 'L',
    defaultWidth: 3,
  },
  // 🛡️ Preparación ejecución – Unidades técnicas (6 perfiles)
  {
    id: 'prep-tech-velocidades',
    widgetId: WidgetId.EXECUTION_PREP_TECH,
    techProfile: 'velocidades',
    title: 'Preparación ejecución – Velocidades',
    description: 'Indicar preparación del técnico de balistíca (velocidades) para el inicio de series',
    category: 'Balistíca',
    badge: 'S',
    badgeColor: 'purple',
    defaultWidth: 1,
  },
  {
    id: 'prep-tech-presiones',
    widgetId: WidgetId.EXECUTION_PREP_TECH,
    techProfile: 'presiones',
    title: 'Preparación ejecución – Presiones',
    description: 'Indicar preparación del técnico de balistíca (presiones) para el inicio de series',
    category: 'Balistíca',
    badge: 'S',
    badgeColor: 'purple',
    defaultWidth: 1,
  },
  {
    id: 'prep-tech-video',
    widgetId: WidgetId.EXECUTION_PREP_TECH,
    techProfile: 'video',
    title: 'Preparación ejecución – Vídeo',
    description: 'Indicar preparación del técnico de balistíca (cámaras de vídeo) para el inicio de series',
    category: 'Balistíca',
    badge: 'S',
    badgeColor: 'purple',
    defaultWidth: 1,
  },
  {
    id: 'prep-tech-trayectografia',
    widgetId: WidgetId.EXECUTION_PREP_TECH,
    techProfile: 'trayectografia',
    title: 'Preparación ejecución – Trayectografía',
    description: 'Indicar preparación del técnico de balistíca (radar) para el inicio de series',
    category: 'Balistíca',
    badge: 'S',
    badgeColor: 'purple',
    defaultWidth: 1,
  },
  {
    id: 'prep-tech-municiones',
    widgetId: WidgetId.EXECUTION_PREP_TECH,
    techProfile: 'municiones',
    title: 'Preparación ejecución – Municiones',
    description: 'Indicar preparación del técnico de municiones para el inicio de series',
    category: 'Municiones',
    badge: 'S',
    badgeColor: 'purple',
    defaultWidth: 1,
  },
  {
    id: 'prep-tech-armamento',
    widgetId: WidgetId.EXECUTION_PREP_TECH,
    techProfile: 'armamento',
    title: 'Preparación ejecución – Armamento',
    description: 'Indicar preparación del técnico de armamento para el inicio de series',
    category: 'Armamento',
    badge: 'S',
    badgeColor: 'purple',
    defaultWidth: 1,
  },
  {
    id: 'prep-jlt',
    widgetId: WidgetId.EXECUTION_PREP_JLT,
    title: 'Preparación ejecución – JLT',
    description: 'Control de preparación de series y disparos para el Jefe de Línea de Tiro',
    category: 'Jefe línea de tiro',
    badge: 'L',
    defaultWidth: 3,
  },
  {
    id: 'orientacion-camaras-video',
    widgetId: WidgetId.VIDEO_CAMERA_ORIENTATION,
    title: 'Orientación cámaras de vídeo',
    description: 'Configuración de cámara, distancia, altura, alcance y diferencia angular',
    category: 'Balística',
    badge: 'S',
    badgeColor: 'purple',
    defaultWidth: 1,
    defaultHeight: 2,
  },
  {
    id: 'orientacion-radar-trayectografia',
    widgetId: WidgetId.RADAR_TRAYECTOGRAPHY_ORIENTATION,
    title: 'Orientación radar de trayectografía',
    description: 'Coordenadas pieza, puntos de caída calculados, OLT geográfico y diferencia angular del radar',
    category: 'Balística',
    badge: 'S',
    badgeColor: 'purple',
    defaultWidth: 3,
    defaultHeight: 1,
  },
  {
    id: 'introduccion-datos-topografia-mao',
    widgetId: WidgetId.MAO_TOPOGRAPHY,
    title: 'Introducción de datos Topografía MAO',
    description: 'OLT, coordenadas de pieza y blanco, observador',
    category: 'Topografía',
    badge: 'S',
    badgeColor: 'purple',
    defaultWidth: 3,
    defaultHeight: 1,
  },
  {
    id: 'introduccion-datos-jlt-mao',
    widgetId: WidgetId.JLT_MAO,
    title: 'TRIAL_EXECUTION.WIDGETS.JLT_MAO.TITLE',
    description: 'TRIAL_EXECUTION.WIDGETS.JLT_MAO.DESCRIPTION',
    category: 'Jefe línea de tiro',
    badge: 'J',
    badgeColor: 'purple',
    defaultWidth: 3,
    defaultHeight: 1,
  },
  {
    id: 'introduccion-datos-armamento',
    widgetId: WidgetId.ARMAMENT_INTRODUCTION,
    title: 'TRIAL_EXECUTION.WIDGETS.ARMAMENT_INTRODUCTION.TITLE',
    description: 'TRIAL_EXECUTION.WIDGETS.ARMAMENT_INTRODUCTION.DESCRIPTION',
    category: 'Municiones',
    badge: 'M',
    badgeColor: 'blue',
    defaultWidth: 3,
    defaultHeight: 1,
  },
  {
    id: 'introduccion-datos-municion',
    widgetId: WidgetId.MUNITION_INTRODUCTION,
    title: 'TRIAL_EXECUTION.WIDGETS.MUNITION_INTRODUCTION.TITLE',
    description: 'TRIAL_EXECUTION.WIDGETS.MUNITION_INTRODUCTION.DESCRIPTION',
    category: 'Municiones',
    badge: 'M',
    badgeColor: 'blue',
    defaultWidth: 3,
    defaultHeight: 1,
  },
  {
    id: 'radar-trayectografia-metcmq',
    widgetId: WidgetId.RADAR_METCMQ,
    title: 'TRIAL_EXECUTION.WIDGETS.RADAR_METCMQ.TITLE',
    description: 'TRIAL_EXECUTION.WIDGETS.RADAR_METCMQ.DESCRIPTION',
    category: 'TRIAL_EXECUTION.CATEGORIES.BALISTICA',
    badge: 'B',
    badgeColor: 'purple',
    defaultWidth: 1,
    defaultHeight: 1,
  },
  {
    id: 'introduccion-datos-jlt',
    widgetId: WidgetId.JLT_SHOT_DATA,
    title: 'TRIAL_EXECUTION.WIDGETS.JLT_SHOT_DATA.TITLE',
    description: 'TRIAL_EXECUTION.WIDGETS.JLT_SHOT_DATA.DESCRIPTION',
    category: 'Jefe línea de tiro',
    badge: 'J',
    badgeColor: 'purple',
    defaultWidth: 3,
    defaultHeight: 1,
  },
  {
    id: 'introduccion-datos-presion-manometros',
    widgetId: WidgetId.MANOMETER_INTRODUCTION,
    title: 'TRIAL_EXECUTION.WIDGETS.MANOMETER_INTRODUCTION.TITLE',
    description: 'TRIAL_EXECUTION.WIDGETS.MANOMETER_INTRODUCTION.DESCRIPTION',
    category: 'Balística',
    badge: 'B',
    badgeColor: 'purple',
    defaultWidth: 3,
    defaultHeight: 1,
  },
  {
    id: 'introduccion-datos-presion-piezo',
    widgetId: WidgetId.PIEZO_PRESSURE_INTRODUCTION,
    title: 'TRIAL_EXECUTION.WIDGETS.PIEZO_PRESSURE.TITLE',
    description: 'TRIAL_EXECUTION.WIDGETS.PIEZO_PRESSURE.DESCRIPTION',
    category: 'Balística',
    badge: 'B',
    badgeColor: 'blue',
    defaultWidth: 3,
    defaultHeight: 1,
  },
  {
    id: 'introduccion-datos-velocidades',
    widgetId: WidgetId.VELOCITY_INTRODUCTION,
    title: 'TRIAL_EXECUTION.WIDGETS.VELOCITY_INTRODUCTION.TITLE',
    description: 'TRIAL_EXECUTION.WIDGETS.VELOCITY_INTRODUCTION.DESCRIPTION',
    category: 'Balística',
    badge: 'B',
    badgeColor: 'purple',
    defaultWidth: 3,
    defaultHeight: 1,
  },
  {
    id: 'tarado-velocidad-chart',
    widgetId: WidgetId.TARADO_VELOCIDAD_CHART,
    title: 'TRIAL_EXECUTION.WIDGETS.TARADO_VELOCIDAD.TITLE',
    description: 'TRIAL_EXECUTION.WIDGETS.TARADO_VELOCIDAD.DESCRIPTION',
    category: 'Balística',
    badge: 'B',
    badgeColor: 'purple',
    defaultWidth: 1,
    defaultHeight: 2,
  },
  {
    id: 'tarado-presion-chart',
    widgetId: WidgetId.TARADO_PRESION_CHART,
    title: 'TRIAL_EXECUTION.WIDGETS.TARADO_PRESION.TITLE',
    description: 'TRIAL_EXECUTION.WIDGETS.TARADO_PRESION.DESCRIPTION',
    category: 'Balística',
    badge: 'B',
    badgeColor: 'purple',
    defaultWidth: 1,
    defaultHeight: 2,
  },
  {
    id: 'trayectografia-introduction',
    widgetId: WidgetId.TRAYECTOGRAFIA_INTRODUCTION,
    title: 'TRIAL_EXECUTION.WIDGETS.TRAYECTOGRAFIA_INTRODUCTION.TITLE',
    description: 'TRIAL_EXECUTION.WIDGETS.TRAYECTOGRAFIA_INTRODUCTION.DESCRIPTION',
    category: 'Trayectografía',
    badge: 'S',
    badgeColor: 'purple',
    defaultWidth: 3,
    defaultHeight: 1,
  },
  {
    id: 'stanag-criterios',
    widgetId: WidgetId.STANAG_CRITERIOS,
    title: 'TRIAL_EXECUTION.WIDGETS.STANAG_CRITERIOS.TITLE',
    description: 'TRIAL_EXECUTION.WIDGETS.STANAG_CRITERIOS.DESCRIPTION',
    category: 'Balística',
    badge: 'S',
    badgeColor: 'purple',
    defaultWidth: 1,
    defaultHeight: 2,
  },
  {
    id: 'uniformidad-chart',
    widgetId: WidgetId.UNIFORMIDAD_CHART,
    title: 'TRIAL_EXECUTION.WIDGETS.UNIFORMIDAD.TITLE',
    description: 'TRIAL_EXECUTION.WIDGETS.UNIFORMIDAD.DESCRIPTION',
    category: 'Balística',
    badge: 'B',
    badgeColor: 'purple',
    defaultWidth: 1,
    defaultHeight: 2,
  },
  {
    id: 'seguimiento',
    widgetId: WidgetId.SEGUIMIENTO,
    title: 'TRIAL_EXECUTION.WIDGETS.SEGUIMIENTO.TITLE',
    description: 'TRIAL_EXECUTION.WIDGETS.SEGUIMIENTO.DESCRIPTION',
    category: 'Balística',
    badge: 'S',
    badgeColor: 'purple',
    defaultWidth: 1,
    defaultHeight: 2,
  },
  {
    id: 'informacion-tarado',
    widgetId: WidgetId.INFORMACION_TARADO,
    title: 'TRIAL_EXECUTION.WIDGETS.INFORMACION_TARADO.TITLE',
    description: 'TRIAL_EXECUTION.WIDGETS.INFORMACION_TARADO.DESCRIPTION',
    category: 'Balística',
    badge: 'S',
    badgeColor: 'purple',
    defaultWidth: 3,
    defaultHeight: 1,
  },
  {
    id: 'overpressure-info',
    widgetId: WidgetId.OVERPRESSURE_INFO,
    title: 'TRIAL_EXECUTION.WIDGETS.OVERPRESSURE_INFO.TITLE',
    description: 'TRIAL_EXECUTION.WIDGETS.OVERPRESSURE_INFO.DESCRIPTION',
    category: 'Presiones',
    badge: 'P',
    badgeColor: 'purple',
    defaultWidth: 1,
    defaultHeight: 1,
  },
  {
    id: 'overpressure-chart',
    widgetId: WidgetId.OVERPRESSURE_CHART,
    title: 'TRIAL_EXECUTION.WIDGETS.OVERPRESSURE_CHART.TITLE',
    description: 'TRIAL_EXECUTION.WIDGETS.OVERPRESSURE_CHART.DESCRIPTION',
    category: 'Presiones',
    badge: 'P',
    badgeColor: 'purple',
    defaultWidth: 2,
    defaultHeight: 1,
  },
  {
    id: 'calculo-coordenadas-paso',
    widgetId: WidgetId.PASS_COORDS,
    title: 'TRIAL_EXECUTION.WIDGETS.PASS_COORDS.TITLE',
    description: 'TRIAL_EXECUTION.WIDGETS.PASS_COORDS.DESCRIPTION',
    category: 'TRIAL_EXECUTION.CATEGORIES.BALISTICA',
    badge: 'B',
    badgeColor: 'purple',
    defaultWidth: 1,
    defaultHeight: 2,
  },
  {
    id: 'criterio-grubbs',
    widgetId: WidgetId.GRUBBS_CRITERION,
    title: 'TRIAL_EXECUTION.WIDGETS.GRUBBS_CRITERION.TITLE',
    description: 'TRIAL_EXECUTION.WIDGETS.GRUBBS_CRITERION.DESCRIPTION',
    category: 'TRIAL_EXECUTION.CATEGORIES.ESTADISTICA',
    badge: 'E',
    badgeColor: 'purple',
    defaultWidth: 1,
    defaultHeight: 1,
  },
  {
    id: 'introduccion-datos-topografia',
    widgetId: WidgetId.TOPOGRAPHY_INTRODUCTION,
    title: 'TRIAL_EXECUTION.WIDGETS.TOPOGRAPHY_INTRODUCTION.TITLE',
    description: 'TRIAL_EXECUTION.WIDGETS.TOPOGRAPHY_INTRODUCTION.DESCRIPTION',
    category: 'Topografía',
    badge: 'S',
    badgeColor: 'purple',
    defaultWidth: 3,
    defaultHeight: 1,
  },
  {
    id: 'datos-del-blanco',
    widgetId: WidgetId.TARGET_DATA,
    title: 'TRIAL_EXECUTION.WIDGETS.TARGET_DATA.TITLE',
    description: 'TRIAL_EXECUTION.WIDGETS.TARGET_DATA.DESCRIPTION',
    category: 'Armamento',
    badge: 'A',
    badgeColor: 'purple',
    defaultWidth: 3,
    defaultHeight: 1,
  },
  {
    id: 'introduccion-datos-nivel-acustico',
    widgetId: WidgetId.ACOUSTIC_LEVEL_INTRODUCTION,
    title: 'TRIAL_EXECUTION.WIDGETS.ACOUSTIC_LEVEL_INTRODUCTION.TITLE',
    description: 'TRIAL_EXECUTION.WIDGETS.ACOUSTIC_LEVEL_INTRODUCTION.DESCRIPTION',
    category: 'Balística',
    badge: 'A',
    badgeColor: 'purple',
    defaultWidth: 3,
    defaultHeight: 1,
  },
  {
    id: 'vigilancia',
    widgetId: WidgetId.VIGILANCIA,
    title: 'TRIAL_EXECUTION.WIDGETS.VIGILANCIA.TITLE',
    description: 'TRIAL_EXECUTION.WIDGETS.VIGILANCIA.DESCRIPTION',
    category: 'TRIAL_EXECUTION.CATEGORIES.ESTADISTICA',
    badge: 'V',
    badgeColor: 'purple',
    defaultWidth: 1,
    defaultHeight: 2,
  },
  {
    id: 'datos-blanco-bola',
    widgetId: WidgetId.DATOS_BLANCO_BOLA,
    title: 'TRIAL_EXECUTION.WIDGETS.DATOS_BLANCO_BOLA.TITLE',
    description: 'TRIAL_EXECUTION.WIDGETS.DATOS_BLANCO_BOLA.DESCRIPTION',
    category: 'Topografía',
    badge: 'T',
    badgeColor: 'purple',
    defaultWidth: 3,
    defaultHeight: 1,
  },
  {
    id: 'seguridad',
    widgetId: WidgetId.SEGURIDAD,
    title: 'TRIAL_EXECUTION.WIDGETS.SEGURIDAD.TITLE',
    description: 'TRIAL_EXECUTION.WIDGETS.SEGURIDAD.DESCRIPTION',
    category: 'Balística',
    badge: 'S',
    badgeColor: 'purple',
    defaultWidth: 1,
    defaultHeight: 2,
  },
];
